# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - First Iteration 2023 v.1.0 

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [2]:
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [7]:

array_10_ones = np.ones (10)
print(array_10_ones)

array_integers = np.arange(1, 20, 1, dtype="int")
print(array_integers)

array_matrix = np.ones((5, 5), dtype="int")
print(array_matrix)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [12]:
arr6 = np.random.randn(3, 3, 3)
print(arr6)

print("two")
arr6e = arr6.reshape(27)
print(arr6e)

[[[ 0.92058582  3.42450885  0.80336424]
  [ 0.73260101  0.09717174  0.28994826]
  [ 0.47066953  0.86834863 -1.33091729]]

 [[ 1.13508096  0.54739089  1.94854309]
  [-0.53145796  0.54933631  0.2295084 ]
  [ 1.20899334  0.11221143  1.40486004]]

 [[-0.375712    0.97009708 -1.30663762]
  [-1.51236657 -2.44170793 -0.83044281]
  [ 1.69354856 -0.23990784 -0.84769597]]]
two
[ 0.92058582  3.42450885  0.80336424  0.73260101  0.09717174  0.28994826
  0.47066953  0.86834863 -1.33091729  1.13508096  0.54739089  1.94854309
 -0.53145796  0.54933631  0.2295084   1.20899334  0.11221143  1.40486004
 -0.375712    0.97009708 -1.30663762 -1.51236657 -2.44170793 -0.83044281
  1.69354856 -0.23990784 -0.84769597]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [13]:
arr5 = np.linspace(1, 10, 20, dtype="int")
print(arr5)


[ 1  1  1  2  2  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10]


## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [17]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
20

In [21]:
print(a[3, 4])

20


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [107]:
# Code come here
import numpy as np
a = np.arange(1, 26).reshape(5, -1)


print; (a[1:5, 3:5])

array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])

```python
array([ 6,  7,  8,  9, 10])
```

In [109]:
a = np.arange(1, 26).reshape(5, -1)

print;(a[1, 0:5])

array([ 6,  7,  8,  9, 10])

## 2.5 

Calculate the sum of all the numbers in `a`.

In [119]:
a = np.arange(1, 26).reshape(5, -1)

np.sum(a)

325

## 2.6 

Calculate the sum of each row in `a`.

In [134]:
a = np.arange(1, 26).reshape(5, -1)
print(a)
print("")
sums = print(np.sum(a,axis=1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

[ 15  40  65  90 115]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [141]:
a = np.arange(1, 26).reshape(5, -1)
mean= np.mean(a)
print(mean)

arrAbool = a[(a>mean)]

print(arrAbool)

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [142]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [143]:
food = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv", sep=",", header=0, encoding="ISO-8859-1")
food.head(10)

country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

## 2.10 

How many rows and columns are there in the dataframe?

In [144]:
len(food)

#Four columns, exlcuding the index and 1430 rows

1430

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [156]:
df= pd.DataFrame(food)

print(df)

dfMean = df["co2_emmission"].mean()

print(dfMean)

         country             food_category  consumption  co2_emmission
0      Argentina                      Pork        10.51          37.20
1      Argentina                   Poultry        38.66          41.53
2      Argentina                      Beef        55.48        1712.00
3      Argentina               Lamb & Goat         1.56          54.63
4      Argentina                      Fish         4.36           6.96
...          ...                       ...          ...            ...
1425  Bangladesh        Milk - inc. cheese        21.91          31.21
1426  Bangladesh  Wheat and Wheat Products        17.47           3.33
1427  Bangladesh                      Rice       171.73         219.76
1428  Bangladesh                  Soybeans         0.61           0.27
1429  Bangladesh   Nuts inc. Peanut Butter         0.72           1.27

[1430 rows x 4 columns]
74.383993006993


## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [168]:
dfMean = df["co2_emmission"].max()
print(dfMean)

food_co2 = df[(df["co2_emmission"] == 1712.0)]
print(food_co2.head(3))

##The maxumum value is in Argentina, with 1712

1712.0
<bound method NDFrame.head of      country food_category  consumption  co2_emmission
2  Argentina          Beef        55.48         1712.0>


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [172]:
food_co2production = df[(df["co2_emmission"] > 1000)]

print(food_co2production.head(10))

print(len(food_co2production))

#Five

       country food_category  consumption  co2_emmission
2    Argentina          Beef        55.48        1712.00
13   Australia          Beef        33.86        1044.85
57         USA          Beef        36.24        1118.29
90      Brazil          Beef        39.25        1211.17
123    Bermuda          Beef        33.15        1022.94
5


## 2.14

Which country consumes the least amount of beef per person per year?


In [184]:
##minimum

dfmin = df["consumption"].min()
print(dfmin)

subset_query = df.query('food_category=="Beef" and consumption < 0.79')
print(subset_query)

##The answer is Liberia, with a consumption of 0.78.

0.0
      country food_category  consumption  co2_emmission
1410  Liberia          Beef         0.78          24.07


## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [273]:
##total emissions of all produtcs, meat and non-meat
dfsum = df["co2_emmission"].sum()
print(dfsum)


SumGrouped = df.groupby(['food_category'])['co2_emmission'].sum()
print(SumGrouped)

print("")



106369.10999999999
food_category
Beef                        48633.26
Eggs                          974.95
Fish                         3588.22
Lamb & Goat                 11837.38
Milk - inc. cheese          23290.00
Nuts inc. Peanut Butter       951.99
Pork                         7419.11
Poultry                      2963.16
Rice                         4886.91
Soybeans                       50.35
Wheat and Wheat Products     1773.78
Name: co2_emmission, dtype: float64



In [276]:
df= pd.DataFrame(food)
df.columns =[column.replace(" ", "_") for column in df.columns]
print(df.head(10))

print("")
print("Beef Type Printed")
print("")



beef_type = df[df.food_category == 'Beef']
fish_type = df[df.food_category == 'Fish']
poultry_type = df[df.food_category == 'Poultry']
lamb_type = df[df.food_category == 'Lamb & Goat']
pork_type = df[df.food_category == 'Pork']

print(beef_type)
print(fish_type)
print(poultry_type)
print(lamb_type)
print(pork_type)

print("")
print("Summed Beef Type")
print("")

print("")
print("Summed Beef")
print("")

BeefSumGrouped = beef_type.groupby(['food_category'])['co2_emmission'].sum()
print(BeefSumGrouped)

print("")

meat_products = pd.concat([beef_type, fish_type, poultry_type, lamb_type, pork_type])
print(meat_products)

MeatSumGrouped = meat_products.groupby(['food_category'])['co2_emmission'].sum()
print(MeatSumGrouped)

print("")

meat_merged = pd.concat([beef_type, fish_type, poultry_type, lamb_type, pork_type])
print(len(df))
print(len(meat_merged))

MeatsSum = meat_merged["co2_emmission"].sum()
print(MeatsSum)


     country             food_category  consumption  co2_emmission
0  Argentina                      Pork        10.51          37.20
1  Argentina                   Poultry        38.66          41.53
2  Argentina                      Beef        55.48        1712.00
3  Argentina               Lamb & Goat         1.56          54.63
4  Argentina                      Fish         4.36           6.96
5  Argentina                      Eggs        11.39          10.46
6  Argentina        Milk - inc. cheese       195.08         277.87
7  Argentina  Wheat and Wheat Products       103.11          19.66
8  Argentina                      Rice         8.77          11.22
9  Argentina                  Soybeans         0.00           0.00

Beef Type Printed

           country food_category  consumption  co2_emmission
2        Argentina          Beef        55.48        1712.00
13       Australia          Beef        33.86        1044.85
24         Albania          Beef        22.50         694.30

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [277]:
df= pd.DataFrame(food)
df.columns =[column.replace(" ", "_") for column in df.columns]

egg_type = df[df.food_category == 'Eggs']
milk_type = df[df.food_category == 'Milk - inc. Peanut Butter']
nuts_type = df[df.food_category == 'Nuts inc. Peanut Butter']
rice_type = df[df.food_category == 'Rice']
soy_type = df[df.food_category == 'Soybeans']
wheat_type = df[df.food_category == 'Wheat and Wheat Products']

nonmeat_products = pd.concat([egg_type, milk_type, nuts_type, rice_type, soy_type, wheat_type])
print(nonmeat_products)

print("Non meats sum grouped")
NonMeatSumGrouped = nonmeat_products.groupby(['food_category'])['co2_emmission'].sum()
print(NonMeatSumGrouped)

nonmeat_merged = pd.concat([egg_type, milk_type, nuts_type, rice_type, soy_type, wheat_type])

NonMeatsSum = nonmeat_merged["co2_emmission"].sum()
print(NonMeatsSum)


           country             food_category  consumption  co2_emmission
5        Argentina                      Eggs        11.39          10.46
16       Australia                      Eggs         8.51           7.82
27         Albania                      Eggs        12.45          11.44
38         Iceland                      Eggs         8.24           7.57
49     New Zealand                      Eggs         9.91           9.10
...            ...                       ...          ...            ...
1382  Sierra Leone  Wheat and Wheat Products         8.72           1.66
1393     Sri Lanka  Wheat and Wheat Products        37.01           7.06
1404     Indonesia  Wheat and Wheat Products        25.45           4.85
1415       Liberia  Wheat and Wheat Products        10.95           2.09
1426    Bangladesh  Wheat and Wheat Products        17.47           3.33

[650 rows x 4 columns]
Non meats sum grouped
food_category
Eggs                         974.95
Nuts inc. Peanut Butter     

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.